sudo: true
language: node_js
node_js:
  - "8"
services:
  - postgresql
before_install:
  - sudo apt-get update
before_script:
  - psql -c 'create database aqua_test;' -U postgres
  - psql -c "CREATE ROLE aqua_test LOGIN ENCRYPTED PASSWORD 'md512d23bb09f295a82e5a316755dfdc0ca' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;" -U postgres
env:
  - NODE_ENV=test CXX=g++-4.8
before_install:
  - sudo apt-get install unicode-data
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
